module.exports={
    database:"mongodb://localhost:27017/starrysea",
    trustOrigin:[
        "http://localhost:4200",
        "http://localhost:3000",
        "https://starrysea.org",
        "https://www.starrysea.org",
        "https://cn.starrysea.org",
        "https://jp.starrysea.org",
        "http://www.starrysea.top",
    ],
};
